name: Create Release ZIP
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Plugin ZIP
        run: |
          # Create the directory with the exact plugin name
          mkdir teckglobal-brute-force-protect
          # Copy all necessary files into the directory
          cp -r *.php includes assets vendor README.md readme.txt teckglobal-brute-force-protect/
          # Remove any unnecessary files (e.g., .git, workflows)
          rm -rf teckglobal-brute-force-protect/.git* teckglobal-brute-force-protect/.github
          # Create the ZIP with the folder as the root
          zip -r teckglobal-brute-force-protect.zip teckglobal-brute-force-protect
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./teckglobal-brute-force-protect.zip
          asset_name: teckglobal-brute-force-protect.zip
          asset_content_type: application/zip
